/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Owner.OBH;
import Owner.Owner;
import boardinghub.Home;
import Register.Register;
import com.mysql.cj.protocol.Resultset;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Malitha
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BoardingHub = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Password = new javax.swing.JLabel();
        NIC = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LNIC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LPassword = new javax.swing.JPasswordField();
        LReset = new javax.swing.JButton();
        LLogin = new javax.swing.JButton();
        LBack = new javax.swing.JButton();
        LShowPassword = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 119, 209));

        BoardingHub.setBackground(new java.awt.Color(255, 255, 255));
        BoardingHub.setFont(new java.awt.Font("Georgia", 1, 55)); // NOI18N
        BoardingHub.setForeground(new java.awt.Color(255, 255, 255));
        BoardingHub.setText("BoardingHub");
        BoardingHub.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jPanel2.setBackground(new java.awt.Color(29, 119, 209));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 470, 35));

        NIC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NIC.setForeground(new java.awt.Color(255, 255, 255));
        NIC.setText("NIC");
        jPanel2.add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 470, 35));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("_______________________________________________________________________________________________________________");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, 500, 20));

        LNIC.setBackground(new java.awt.Color(29, 119, 209));
        LNIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LNIC.setForeground(new java.awt.Color(255, 255, 255));
        LNIC.setBorder(null);
        LNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNICActionPerformed(evt);
            }
        });
        jPanel2.add(LNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 500, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("_______________________________________________________________________________________________________________");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 146, 500, 20));

        LPassword.setBackground(new java.awt.Color(29, 119, 209));
        LPassword.setForeground(new java.awt.Color(255, 255, 255));
        LPassword.setBorder(null);
        LPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(LPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 237, 500, 35));

        LReset.setText("RESET");
        LReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LResetActionPerformed(evt);
            }
        });
        jPanel2.add(LReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 100, 30));

        LLogin.setText("LOGIN");
        LLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LLoginActionPerformed(evt);
            }
        });
        jPanel2.add(LLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 100, 30));

        LBack.setText("Back");
        LBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LBackActionPerformed(evt);
            }
        });
        jPanel2.add(LBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 120, 30));

        LShowPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        LShowPassword.setText("Show Password");
        LShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LShowPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(LShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 172, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 65)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Login");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -20, 230, 110));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoardingHub)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BoardingHub)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNICActionPerformed

    private void LPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LPasswordActionPerformed

    private void LResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LResetActionPerformed
        // TODO add your handling code here:
        LNIC.setText("");
        LPassword.setText("");
    }//GEN-LAST:event_LResetActionPerformed

    private void LLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LLoginActionPerformed

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
            //select customer 
            String s = "select * from customer where NIC=? and password=?";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, LNIC.getText());
            ps.setString(2, LPassword.getText());
            ResultSet rs = ps.executeQuery();

            //////////////////////////////////////////////////////////////////////////////////
            /// select owners
            String st = "select * from owner where NIC=? and password=?";
            PreparedStatement pst = con.prepareStatement(st);
            pst.setString(1, LNIC.getText());
            pst.setString(2, LPassword.getText());
            ResultSet rst = pst.executeQuery();

            ////////////////////////////////////////////////////
            ///Select Admin
            String sa = "select * from admin where ID=? and Password=?";
            PreparedStatement psa = con.prepareStatement(sa);
            psa.setString(1, LNIC.getText());
            psa.setString(2, LPassword.getText());
            ResultSet rsa = psa.executeQuery();

            //cheak customer     
            if (rs.next()) {
                String ID = rs.getString("NIC");
                JOptionPane.showMessageDialog(this, "Boader Login Succesfully");
                this.setVisible(false);

                String username = rs.getString("Fname");
                new Home(username).setVisible(true);
            } /// cheak owners
            else if (rst.next()) {
                String ID = rst.getString("NIC");
                JOptionPane.showMessageDialog(this, "Owner Login Succesfully");
                this.setVisible(false);

                String ONIC = rst.getString("NIC");
                String Fusername = rst.getString("Fname");
                String Lusername = rst.getString("Lname");
                new Owner(Fusername, Lusername, ONIC).setVisible(true);

            } //cheak admin  
            else if (rsa.next()) {
                //int ID =rsa.getInt("ID");
                JOptionPane.showMessageDialog(this, "ADDMIN Login Succesfully");
                this.setVisible(false);

                String username = rsa.getString("Name");
                new Home(username).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Login Failed", "Message", JOptionPane.ERROR_MESSAGE);
                LNIC.setText("");
                LPassword.setText("");
            }
        } catch (HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e) {

            System.out.println(e);

        }

    }//GEN-LAST:event_LLoginActionPerformed

    private void LBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LBackActionPerformed
        // TODO add your handling code here:
        Home reg1 = new Home();
        reg1.show();
        this.dispose();
        reg1.setVisible(true);
    }//GEN-LAST:event_LBackActionPerformed

    private void LShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LShowPasswordActionPerformed
        // TODO add your handling code here:
        if (LShowPassword.isSelected()) {
            LPassword.setEchoChar((char) 0);
        } else {
            LPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_LShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoardingHub;
    private javax.swing.JButton LBack;
    private javax.swing.JButton LLogin;
    private javax.swing.JTextField LNIC;
    private javax.swing.JPasswordField LPassword;
    private javax.swing.JButton LReset;
    private javax.swing.JCheckBox LShowPassword;
    private javax.swing.JLabel NIC;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
