/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boardinghub;

import Register.Register;
import Login.Login;
import Boarding.BH_add;
import java.awt.Color;

/**
 *
 * @author Malitha
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Color DefaultColor,ClickedColor;
    public Home() {
        initComponents();
        DefaultColor =new Color (231,55,245);
        ClickedColor =new Color (13,255,255);
        //set Default color to pan on run time
        HLogin.setBackground(DefaultColor);
        HRegister.setBackground(DefaultColor);
       
       
    }
    public Home(String User) {
        initComponents();
        Huser.setText(User);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Footer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        BoardingHub = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        HLogin = new javax.swing.JButton();
        HBoardingHouse = new javax.swing.JButton();
        MAnex = new javax.swing.JButton();
        MAbout = new javax.swing.JButton();
        HRegister = new javax.swing.JButton();
        a = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Huser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Footer.setBackground(new java.awt.Color(29, 119, 209));
        Footer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        Footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("⭕⭕⭕ DSML SOLUTIONS ⭕⭕⭕");
        Footer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 190, 30));

        getContentPane().add(Footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1020, 40));

        jPanel1.setBackground(new java.awt.Color(29, 119, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3Bhub.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 380, 360));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        BoardingHub.setBackground(new java.awt.Color(255, 255, 255));
        BoardingHub.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        BoardingHub.setText("BoardingHub");
        BoardingHub.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Custom-Icon-Design-Mono-General-1-Close.24.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(BoardingHub, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 498, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(BoardingHub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        jPanel2.setBackground(new java.awt.Color(29, 119, 209));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setAutoscrolls(true);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        HLogin.setBackground(new java.awt.Color(29, 119, 209));
        HLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HLogin.setForeground(new java.awt.Color(255, 255, 255));
        HLogin.setText("Login");
        HLogin.setBorder(null);
        HLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HLoginMousePressed(evt);
            }
        });
        HLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HLoginActionPerformed(evt);
            }
        });

        HBoardingHouse.setBackground(new java.awt.Color(29, 119, 209));
        HBoardingHouse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HBoardingHouse.setForeground(new java.awt.Color(255, 255, 255));
        HBoardingHouse.setText("BoardingHouse");
        HBoardingHouse.setBorder(null);
        HBoardingHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HBoardingHouseActionPerformed(evt);
            }
        });

        MAnex.setBackground(new java.awt.Color(29, 119, 209));
        MAnex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MAnex.setForeground(new java.awt.Color(255, 255, 255));
        MAnex.setText("Anex");
        MAnex.setBorder(null);
        MAnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAnexActionPerformed(evt);
            }
        });

        MAbout.setBackground(new java.awt.Color(29, 119, 209));
        MAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MAbout.setForeground(new java.awt.Color(255, 255, 255));
        MAbout.setText("About");
        MAbout.setBorder(null);
        MAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAboutActionPerformed(evt);
            }
        });

        HRegister.setBackground(new java.awt.Color(29, 119, 209));
        HRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HRegister.setForeground(new java.awt.Color(255, 255, 255));
        HRegister.setText("Register");
        HRegister.setBorder(null);
        HRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HRegisterMousePressed(evt);
            }
        });
        HRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRegisterActionPerformed(evt);
            }
        });

        a.setForeground(new java.awt.Color(255, 255, 255));
        a.setText("jLabel5");
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HBoardingHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAnex, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(HLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HBoardingHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MAnex, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 25, 210, 510));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, 91, 84));

        Huser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Huser.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.add(Huser, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HLoginActionPerformed
        // TODO add your handling code here:
        Login reg1 =new Login();
        reg1.show();
        this.dispose();
        reg1.setVisible(true);
    }//GEN-LAST:event_HLoginActionPerformed

    private void HBoardingHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HBoardingHouseActionPerformed
        // TODO add your handling code here:
        BH_add reg1 =new BH_add();
        reg1.show();
        this.dispose();
        reg1.setVisible(true);
    }//GEN-LAST:event_HBoardingHouseActionPerformed

    private void MAnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAnexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MAnexActionPerformed

    private void MAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAboutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MAboutActionPerformed

    private void HRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRegisterActionPerformed
        // TODO add your handling code here:
        Register reg1 =new Register();
        reg1.show();
        this.dispose();
        reg1.setVisible(true);
    }//GEN-LAST:event_HRegisterActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void HLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HLoginMousePressed
        // TODO add your handling code here:
        HLogin.setBackground(ClickedColor);
        HRegister.setBackground(DefaultColor);
        a.setBackground(DefaultColor);
    }//GEN-LAST:event_HLoginMousePressed

    private void HRegisterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HRegisterMousePressed
        // TODO add your handling code here:
        HLogin.setBackground(DefaultColor);
        HRegister.setBackground(ClickedColor);
        a.setBackground(DefaultColor);
    }//GEN-LAST:event_HRegisterMousePressed

    private void aMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMousePressed
        // TODO add your handling code here:
        HLogin.setBackground(DefaultColor);
        HRegister.setBackground(DefaultColor);
        a.setBackground(ClickedColor);
    }//GEN-LAST:event_aMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoardingHub;
    private javax.swing.JPanel Footer;
    private javax.swing.JButton HBoardingHouse;
    private javax.swing.JButton HLogin;
    private javax.swing.JButton HRegister;
    private javax.swing.JLabel Huser;
    private javax.swing.JButton MAbout;
    private javax.swing.JButton MAnex;
    private javax.swing.JLabel a;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
