/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Owner;

import Register.CustomerRegisterform;
import boardinghub.Home;
import java.awt.HeadlessException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Malitha
 */
public class OBH extends javax.swing.JFrame {

    /**
     * Creates new form OBH
     */
    public OBH() {
        initComponents();
        connect();
        AutoID ();
    }
    public OBH(String NIC) {
        initComponents();
        ONICL.setText(NIC);
        connect();
        AutoID ();
   }
    
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    
    public final void connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
        } catch (ClassNotFoundException | SQLException ex) {
           // java.util.logging.Logger.getLogger(ReTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    public void AutoID ()
    {
        
        try {
            Statement s= con.createStatement();
            rs = s.executeQuery("select Max(BID) from boardinghouse");
            rs.next();
            rs.getString("Max(BID)");
            
            
            if(rs.getString("Max(BID)")==null)
            {
            
                BHI.setText("BHI001");
                
            }
            else
            {
                long id = Long.parseLong(rs.getString("Max(BID)").substring(3,rs.getString("Max(BID)").length()));
                id++;
                BHI.setText("BHI"+String.format("%03d", id));
                
                
            }
            
        } catch (SQLException ex) { 
            //java.util.logging.Logger.getLogger(ReTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
    }    
        
    
    /*public void browse(JLabel ABC, byte[] pho){
        
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
        int showOpenDialog = browseImagefile.showOpenDialog(null);
        if (showOpenDialog == JFileChooser.APPROVE_OPTION){
        File selectedImageFile =browseImagefile.getSelectedFile();
        String selectImagePath =selectedImageFile.getAbsolutePath();
        JOptionPane.showConfirmDialog(null, selectImagePath) ;
        
        //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
        filename=selectedImageFile.getAbsolutePath();
        
        
        try {
        File image =new File (filename);
        FileInputStream fis =new FileInputStream(image);
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte [] buf =new byte [488888];
        for (int readNum; (readNum =fis.read(buf))!= -1;){
        bos.write(buf,0,readNum);
        }
        
        photo1 =bos.toByteArray();
        /*photo2 =bos.toByteArray();
        photo3 =bos.toByteArray();
        photo4 =bos.toByteArray();
        
    }
    catch (FileNotFoundException ex) {
    java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IOException e) {
    java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
}
catch (Exception e) {
    JOptionPane.showMessageDialog(null,e );
}
//  return null;
}
//  return null;
   
    }
    //////////////////////////////////////////
    */
        byte[] photo1 =null;
        byte[] photo2 =null;
        byte[] photo3 =null;
        byte[] photo4 =null;
        String filename =null;
    ////////////////////////////////////////

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BoardingHub = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BHAddress = new javax.swing.JTextField();
        BHAvailability = new javax.swing.JTextField();
        BHPrice = new javax.swing.JTextField();
        BHAmenities = new javax.swing.JTextField();
        BHImage1 = new javax.swing.JLabel();
        RBrowse = new javax.swing.JButton();
        RBrowse1 = new javax.swing.JButton();
        BHImage2 = new javax.swing.JLabel();
        RBrowse2 = new javax.swing.JButton();
        BHImage3 = new javax.swing.JLabel();
        RBrowse3 = new javax.swing.JButton();
        BHImage4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ONICL = new javax.swing.JLabel();
        URBack1 = new javax.swing.JButton();
        OBHClear = new javax.swing.JButton();
        BHRegister = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BHLocation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BHI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1031, 576));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(29, 119, 209));

        BoardingHub.setBackground(new java.awt.Color(255, 255, 255));
        BoardingHub.setFont(new java.awt.Font("Georgia", 1, 55)); // NOI18N
        BoardingHub.setForeground(new java.awt.Color(255, 255, 255));
        BoardingHub.setText("BoardingHub");
        BoardingHub.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Availability");

        jLabel4.setText("Address");

        jLabel5.setText("Amenities");

        jLabel6.setText("Price_Range");

        BHAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHAddressActionPerformed(evt);
            }
        });

        BHAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHAvailabilityActionPerformed(evt);
            }
        });

        BHImage1.setText("image1");

        RBrowse.setText("Browse");
        RBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowseActionPerformed(evt);
            }
        });

        RBrowse1.setText("Browse");
        RBrowse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowse1ActionPerformed(evt);
            }
        });

        BHImage2.setText("image2");

        RBrowse2.setText("Browse");
        RBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowse2ActionPerformed(evt);
            }
        });

        BHImage3.setText("image3");

        RBrowse3.setText("Browse");
        RBrowse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowse3ActionPerformed(evt);
            }
        });

        BHImage4.setText("image4");

        jLabel1.setText("NIC");

        ONICL.setText("19992121");

        URBack1.setText("Back");
        URBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URBack1ActionPerformed(evt);
            }
        });

        OBHClear.setText("Clear");
        OBHClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBHClearActionPerformed(evt);
            }
        });

        BHRegister.setText("Register");
        BHRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHRegisterActionPerformed(evt);
            }
        });

        jLabel7.setText("Location");

        BHLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHLocationActionPerformed(evt);
            }
        });

        jLabel8.setText("BID");

        BHI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BHAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BHAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BHAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(BHPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BHLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(BHI, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ONICL, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(BHImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RBrowse1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(BHImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RBrowse))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BHImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BHImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(RBrowse2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RBrowse3, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(72, 72, 72))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(URBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OBHClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BHRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BHI, BHLocation});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ONICL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BHI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BHImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBrowse)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BHImage2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBrowse1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BHImage3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBrowse2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BHImage4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBrowse3))
                        .addGap(101, 101, 101))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHAvailability, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHAmenities, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OBHClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BHRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BHI, BHLocation});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(BoardingHub))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(BoardingHub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage1.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo1 =bos.toByteArray();
           
        }
        catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException e) {
            java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
        
    }//GEN-LAST:event_RBrowseActionPerformed

    private void RBrowse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowse1ActionPerformed
        // TODO add your handling code here:
       JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage2.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo2 =bos.toByteArray();
           
        }
        catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException e) {
            java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
    }//GEN-LAST:event_RBrowse1ActionPerformed

    private void RBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowse2ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage3.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo3 =bos.toByteArray();
           
        }
        catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException e) {
            java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
      //  return null;
   
    
        
        
    }//GEN-LAST:event_RBrowse2ActionPerformed

    private void RBrowse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowse3ActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImagefile = new JFileChooser();
        FileNameExtensionFilter fnet =new FileNameExtensionFilter("jpg","jpeg","png");
        browseImagefile.addChoosableFileFilter(fnet);
        
       int showOpenDialog = browseImagefile.showOpenDialog(null);
       if (showOpenDialog == JFileChooser.APPROVE_OPTION){
           File selectedImageFile =browseImagefile.getSelectedFile();
           String selectImagePath =selectedImageFile.getAbsolutePath();
           JOptionPane.showConfirmDialog(null, selectImagePath) ;
           
           //jLabel2.setIcon(new ImageIcon(selectedImageFile.toString()));
           filename=selectedImageFile.getAbsolutePath();
           BHImage4.setText(filename);
           
           try {
            File image =new File (filename);
            FileInputStream fis =new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf =new byte [488888];
            for (int readNum; (readNum =fis.read(buf))!= -1;){
                bos.write(buf,0,readNum);
            }
             
            photo4 =bos.toByteArray();
           
        }
        catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException e) {
            java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
      //  return null; 
       }
    }//GEN-LAST:event_RBrowse3ActionPerformed

    private void BHAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHAddressActionPerformed

    private void BHAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHAvailabilityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHAvailabilityActionPerformed

    private void URBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URBack1ActionPerformed
        // TODO add your handling code here:
        Owner reg1 =new Owner();
        reg1.show();
        this.dispose();
        reg1.setVisible(true);
    }//GEN-LAST:event_URBack1ActionPerformed

    private void BHRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHRegisterActionPerformed
        // TODO add your handling code here:
        String BHID = BHI.getText();
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
            String s = "Insert into boardinghouse values (?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, BHID);
            ps.setString(2, BHLocation.getText());
            ps.setString(3, BHAddress.getText());
            ps.setString(4, BHAvailability.getText());
            ps.setString(5, BHPrice.getText());
            ps.setString(6, BHAmenities.getText());
            ps.setString(7, ONICL.getText());
            ps.setBytes(8,photo1 );
            ps.setBytes(9,photo2 );
            ps.setBytes(10,photo3 );
            ps.setBytes(11,photo4 );
            
            
            int rs1 = ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Boarding House Register Succesfully");
            //BHI.setText("");
            BHLocation.setText("");
            BHAddress.setText("");
            BHAvailability.setText("");
            BHPrice.setText("");
            BHAmenities.setText("");
            ONICL.setText("");
            BHImage1.setText("");
            BHImage2.setText("");
            BHImage3.setText("");
            BHImage4.setText("");
            
                ps.close();
                con.close();
                
                
            
        }

        catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this,"Boarding House Register UNSuccesfully","Message",JOptionPane.ERROR_MESSAGE);
           

        }

    }//GEN-LAST:event_BHRegisterActionPerformed

    private void BHLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHLocationActionPerformed

    private void OBHClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBHClearActionPerformed
        // TODO add your handling code here:
            BHLocation.setText("");
            BHAddress.setText("");
            BHAvailability.setText("");
            BHPrice.setText("");
            BHAmenities.setText("");
            BHImage1.setText("");
            BHImage2.setText("");
            BHImage3.setText("");
            BHImage4.setText("");
            
    }//GEN-LAST:event_OBHClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OBH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BHAddress;
    private javax.swing.JTextField BHAmenities;
    private javax.swing.JTextField BHAvailability;
    private javax.swing.JLabel BHI;
    private javax.swing.JLabel BHImage1;
    private javax.swing.JLabel BHImage2;
    private javax.swing.JLabel BHImage3;
    private javax.swing.JLabel BHImage4;
    private javax.swing.JTextField BHLocation;
    private javax.swing.JTextField BHPrice;
    private javax.swing.JButton BHRegister;
    private javax.swing.JLabel BoardingHub;
    private javax.swing.JButton OBHClear;
    private javax.swing.JLabel ONICL;
    private javax.swing.JButton RBrowse;
    private javax.swing.JButton RBrowse1;
    private javax.swing.JButton RBrowse2;
    private javax.swing.JButton RBrowse3;
    private javax.swing.JButton URBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
