/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Register;

import boardinghub.Home;
import java.awt.HeadlessException;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Malitha
 */
public class CustomerRegisterform extends javax.swing.JFrame {

    /**
     * Creates new form Registerform
     */
    public CustomerRegisterform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RAdderss = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        RUtype = new javax.swing.JLabel();
        RNIC = new javax.swing.JLabel();
        RFname = new javax.swing.JLabel();
        RSname = new javax.swing.JLabel();
        REmail = new javax.swing.JLabel();
        RPhone = new javax.swing.JLabel();
        RImage_of_NIC = new javax.swing.JLabel();
        RUType = new javax.swing.JComboBox<>();
        URNIC = new javax.swing.JTextField();
        URFName = new javax.swing.JTextField();
        URSName = new javax.swing.JTextField();
        URAdderss = new javax.swing.JTextField();
        UREmail = new javax.swing.JTextField();
        URPhone = new javax.swing.JTextField();
        RPhone1 = new javax.swing.JLabel();
        UR_U_S_J = new javax.swing.JTextField();
        RBrowse = new javax.swing.JButton();
        RNIC1 = new javax.swing.JLabel();
        RNIC2 = new javax.swing.JLabel();
        URPassword = new javax.swing.JPasswordField();
        URCPassword = new javax.swing.JPasswordField();
        URCheak = new javax.swing.JCheckBox();
        URClear = new javax.swing.JButton();
        URegister = new javax.swing.JButton();
        URImage = new javax.swing.JLabel();
        URBack = new javax.swing.JButton();
        RAdderss1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BoardingHub = new javax.swing.JLabel();

        RAdderss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RAdderss.setText("Adderss");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RegisterForm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Emoji", 1, 18))); // NOI18N

        RUtype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RUtype.setText("User Type");

        RNIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RNIC.setText("NIC");

        RFname.setBackground(new java.awt.Color(54, 161, 212));
        RFname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RFname.setText("Frist Name");

        RSname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RSname.setText("Second Name ");

        REmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        REmail.setText("Email");

        RPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RPhone.setText("Phone Number");

        RImage_of_NIC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RImage_of_NIC.setText("Image of NIC");

        RUType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Employee" }));
        RUType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUTypeActionPerformed(evt);
            }
        });

        URNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URNICActionPerformed(evt);
            }
        });

        URFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URFNameActionPerformed(evt);
            }
        });

        URSName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URSNameActionPerformed(evt);
            }
        });

        RPhone1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RPhone1.setText("University/School/WorkPlace\t");

        RBrowse.setText("Browse");
        RBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBrowseActionPerformed(evt);
            }
        });

        RNIC1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RNIC1.setText("Password");

        RNIC2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RNIC2.setText("Confirm Password");

        URCheak.setText("I accept the terms of use & privacy policy");
        URCheak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URCheakActionPerformed(evt);
            }
        });

        URClear.setText("Clear");
        URClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URClearActionPerformed(evt);
            }
        });

        URegister.setText("Register");
        URegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URegisterActionPerformed(evt);
            }
        });

        URBack.setText("Back");
        URBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URBackActionPerformed(evt);
            }
        });

        RAdderss1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RAdderss1.setText("Adderss");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RUtype, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RUType, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RFname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RSname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(REmail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RAdderss1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(URFName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URAdderss, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URSName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UREmail, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UR_U_S_J, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(RPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(RNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RImage_of_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(URNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(URImage, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(RBrowse))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(URCheak, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(URClear, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(URegister, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(RNIC2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(URCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(URPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(URBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RUtype, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RUType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(URNIC, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(URImage, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBrowse)
                            .addComponent(RImage_of_NIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RNIC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RNIC2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URCPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(URCheak))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RFname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URFName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RSname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URSName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(URAdderss, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RAdderss1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(REmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UREmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(URPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(URClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(URegister, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(URBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UR_U_S_J, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, 400));

        jPanel2.setBackground(new java.awt.Color(29, 119, 209));

        BoardingHub.setBackground(new java.awt.Color(255, 255, 255));
        BoardingHub.setFont(new java.awt.Font("Georgia", 1, 55)); // NOI18N
        BoardingHub.setForeground(new java.awt.Color(255, 255, 255));
        BoardingHub.setText("BoardingHub");
        BoardingHub.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(BoardingHub)
                .addGap(319, 319, 319))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BoardingHub)
                .addContainerGap(491, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RUTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RUTypeActionPerformed

    private void URNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URNICActionPerformed

    private void URFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URFNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URFNameActionPerformed

    private void URSNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URSNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URSNameActionPerformed

    private void RBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser =new JFileChooser();
        fileChooser.showOpenDialog(null); ///select file to open
        File f = fileChooser.getSelectedFile();
       // URImage.setIcon(new ImageIcon(f.toString())); ///image file show 
        filename=f.getAbsolutePath();
        URImage.setText(filename);  ///file name 
        
        
            try {
                File image =new File (filename);
                FileInputStream fis =new FileInputStream(image);
                ByteArrayOutputStream bos = new ByteArrayOutputStream();
                byte [] buf =new byte [2048];
                for (int readNum; (readNum =fis.read(buf))!= -1;){
                    bos.write(buf,0,readNum);
                }
                photo =bos.toByteArray();
                
                
            } 
            catch (FileNotFoundException ex) {
                Logger.getLogger(CustomerRegisterform.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException e) {
            Logger.getLogger(CustomerRegisterform.class.getName()).log(Level.SEVERE, null, e);
            }
            catch (Exception e) {
            JOptionPane.showMessageDialog(null,e );
            }
            
        
        
        
    }//GEN-LAST:event_RBrowseActionPerformed

    private void URCheakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URCheakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URCheakActionPerformed

    private void URegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URegisterActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
            String s = "Insert into customer values (?,?,?,?,?,?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, URNIC.getText());
            ps.setString(2, URFName.getText());
            ps.setString(3, URSName.getText());
            ps.setString(4, URAdderss.getText());
            ps.setString(5, UREmail.getText());
            String emailPattern = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    if (!UREmail.getText().matches(emailPattern)) {
    JOptionPane.showMessageDialog(this, "Invalid Email Address");
    UREmail.setText("");
    return;
}
            ps.setString(6, UR_U_S_J.getText());
            ps.setString(7, RUType.getSelectedItem().toString());
            ps.setString(8, URPassword.getText());
            ps.setBytes(9, photo);
            
            
         
            
            String st = "Insert into costomerphone(NIC,Phone_number) values (?,?)";
            PreparedStatement pst = con.prepareStatement(st);
            pst.setString(1,URNIC.getText());
            pst.setString(2, URPhone.getText());
            String phonePattern = "\\d{10}";
if (!URPhone.getText().matches(phonePattern)) {
    JOptionPane.showMessageDialog(this, "Invalid Phone Number");
    URPhone.setText("");
    return;
}
            
            
            if(!(new String(URPassword.getPassword()).endsWith(new String(URCPassword.getPassword()))))
            {
                JOptionPane.showMessageDialog(this, "Youre password Does not Match","Message",JOptionPane.ERROR_MESSAGE);
                URPassword.setText("");
                URCPassword.setText("");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Register Successfully");
                
                 int rs = ps.executeUpdate();
                 int rst = pst.executeUpdate();
                 
                 /*JOptionPane.showMessageDialog(URegister ,rs + rst); */
        
        URNIC.setText("");
        URFName.setText("");
        URSName.setText("");
        URAdderss.setText("");
        UREmail.setText("");
        UR_U_S_J.setText("");
        URPhone.setText("");
        RUType.setSelectedItem("");
        URPassword.setText("");
        URCPassword.setText("");
        //The close() method is used to close the stream and release 
        //the resources that were busy in the stream
        ps.close();
        con.close();
        
        Home reg1 =new Home();
                reg1.show();
                this.dispose();
                reg1.setVisible(true);
            
            
        }
            }
                
      
        
        catch(HeadlessException | ClassNotFoundException | SQLException e){
        
            System.out.println(e);
        
        }
        
   
        
    }//GEN-LAST:event_URegisterActionPerformed

    private void URClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URClearActionPerformed
        // TODO add your handling code here:
        URNIC.setText("");
        URFName.setText("");
        URSName.setText("");
        URAdderss.setText("");
        UREmail.setText("");
        UR_U_S_J.setText("");
        URPhone.setText("");
        RUType.setSelectedItem("");
        URPassword.setText("");
        URCPassword.setText("");
    }//GEN-LAST:event_URClearActionPerformed

    private void URBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URBackActionPerformed
        // TODO add your handling code here:
        Register reg1 =new Register();
        reg1.show();
        this.dispose();
        reg1.setVisible(true);
    }//GEN-LAST:event_URBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerRegisterform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerRegisterform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BoardingHub;
    private javax.swing.JLabel RAdderss;
    private javax.swing.JLabel RAdderss1;
    private javax.swing.JButton RBrowse;
    private javax.swing.JLabel REmail;
    private javax.swing.JLabel RFname;
    private javax.swing.JLabel RImage_of_NIC;
    private javax.swing.JLabel RNIC;
    private javax.swing.JLabel RNIC1;
    private javax.swing.JLabel RNIC2;
    private javax.swing.JLabel RPhone;
    private javax.swing.JLabel RPhone1;
    private javax.swing.JLabel RSname;
    private javax.swing.JComboBox<String> RUType;
    private javax.swing.JLabel RUtype;
    private javax.swing.JTextField URAdderss;
    private javax.swing.JButton URBack;
    private javax.swing.JPasswordField URCPassword;
    private javax.swing.JCheckBox URCheak;
    private javax.swing.JButton URClear;
    private javax.swing.JTextField UREmail;
    private javax.swing.JTextField URFName;
    private javax.swing.JLabel URImage;
    private javax.swing.JTextField URNIC;
    private javax.swing.JPasswordField URPassword;
    private javax.swing.JTextField URPhone;
    private javax.swing.JTextField URSName;
    private javax.swing.JTextField UR_U_S_J;
    private javax.swing.JButton URegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
byte[] photo =null;
String filename =null; 

}
