/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Boarding;
import com.mysql.cj.protocol.Resultset;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class BH_add extends javax.swing.JFrame {

    /**
     * Creates new form BH_add
     */
    public BH_add() {
        initComponents();
    }
    public BH_add(String Addr,
                  String loaction,
                  String BID,
                  String img1
                  ) 
    {
        
        initComponents();
         BHaddress.setText(Addr);
         loca.setText(loaction);
         BIDNum.setText(BID);
         image1.setText (img1);
        
        // NIC1.setText("21331");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JPanel();
        BIDSearch = new javax.swing.JTextField();
        BAddress = new javax.swing.JLabel();
        BLocation = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        BHaddress = new javax.swing.JTextField();
        loca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        BIDSearch1 = new javax.swing.JTextField();
        BIDNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NIC1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BIDSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIDSearchActionPerformed(evt);
            }
        });
        search.add(BIDSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, -1));

        BAddress.setText("address");
        search.add(BAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, 20));

        BLocation.setText("location");
        search.add(BLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 140, -1));
        search.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 390, 320));

        image2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1BHub.jpeg"))); // NOI18N
        image2.setText("image2");
        search.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 350, 230));

        BHaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHaddressActionPerformed(evt);
            }
        });
        search.add(BHaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 300, 25));

        loca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locaActionPerformed(evt);
            }
        });
        search.add(loca, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 300, 25));

        jLabel1.setText("BID");
        search.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 60, 20));

        Search.setText("search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        search.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 70, 20));

        BIDSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIDSearch1ActionPerformed(evt);
            }
        });
        search.add(BIDSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 150, -1));

        BIDNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIDNumActionPerformed(evt);
            }
        });
        search.add(BIDNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 300, 25));

        jLabel2.setText("BID");
        search.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 60, 20));

        NIC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIC1ActionPerformed(evt);
            }
        });
        search.add(NIC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 60, 190, 30));

        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BIDSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIDSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIDSearchActionPerformed

    private void BHaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BHaddressActionPerformed

    private void locaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locaActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/boardinghub", "root", "");
          
            String s = "select * from boardinghouse where BID=? ";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1,BIDSearch.getText());
           
            ResultSet rs = ps.executeQuery();
            
            
            
            
                    
            if(rs.next())
            {
            String ID =rs.getString("BID");
            
                
                String Address =rs.getString("Address"); 
                String loaction =rs.getString("location");
                String BID =rs.getString("BID");      
                 String img1 =rs.getString("BHImage");
                
                new BH_add(Address,loaction,BID,img1).setVisible(true);
                this.dispose();
           }
            else{JOptionPane.showMessageDialog(this,"Search UNSuccesfully","error",JOptionPane.ERROR_MESSAGE);
            BIDSearch.setText("");
            
            } 
         
        }catch(HeadlessException | ClassNotFoundException |NumberFormatException | SQLException e){

            System.out.println(e);
        }
        
        
    
    }//GEN-LAST:event_SearchActionPerformed

    private void BIDSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIDSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIDSearch1ActionPerformed

    private void BIDNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIDNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIDNumActionPerformed

    private void NIC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BH_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BH_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BH_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BH_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BH_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BAddress;
    private javax.swing.JTextField BHaddress;
    private javax.swing.JTextField BIDNum;
    private javax.swing.JTextField BIDSearch;
    private javax.swing.JTextField BIDSearch1;
    private javax.swing.JLabel BLocation;
    private javax.swing.JTextField NIC1;
    private javax.swing.JButton Search;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField loca;
    private javax.swing.JPanel search;
    // End of variables declaration//GEN-END:variables

    private void elseif(int BHI008) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
